### ISSUE TITLE
ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by nygma2004** [coderpussy/MMM-HVIEW-Snapshot#1]
Hi,

I am trying to use your module for the same purpuse, but with different camera. Mine also have a URL access with returns a simple JPG still image. I did the configuration, I checked the URL, I see the image in a browser.
But when I look at the logs, I see
```
Failed to load URL: xxxx with error: ERR_BLOCKED_BY_RESPONSE
```
Did you have similar issues?

**Comment by coderpussy** [comment]
Hi,

sorry for the late response. I haven't any issues with that. My camera is in the same network IP address range as my mirror. Camera URL in module config points to IP address. Furthermore i changed in MagicMirror config.js:

```
var config = {
    address: "0.0.0.0",    // to listen on any interface
    ipWhitelist: []        // allow all IP addresses
}
```

The error you posted says something like your camera isn't in the same domain or location like your mirror. But this is just guessing. What kind of URL you use in your module config pointing to your camera still image?

**Comment by nygma2004** [comment]
No worries, holidays take time off from projects for me too. And Happy New Year!
I was also thinking that the settings are incorrect, but I actually enabled communication on my local subnet so I can access it remotely as well:
```
address: "0.0.0.0",
ipWhitelist: [["192.168.1.0","192.168.1.253"],"127.0.0.1", "::ffff:127.0.0.1", "::1"],
```
That should enable all connections from the 192.168.1.x network. And I am able to SSH into the PI, so it works.
The IP of the magic mirror is also in the 192.168.1.x subnet.
And the IP camera URL is the following:
```
http://192.168.1.82/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=abcd1234&user=xxx&password=xxx
```
And of course this works if I just open in the browser...

So I am not sure what the issue is.

**Comment by coderpussy** [comment]
Have you tried to add the "sandbox" attribute to the iframe tag inside njk template file? But this depends on your exact error message ERR_BLOCKED_BY_RESPONSE. If you open your mirror inside Chrome browser for example, then you should be able to visit network tab on browser dev. console. The header and/or response tab show you what's going on.

If you want to try that sandbox attribute, take a look at the definitions for example:
https://www.w3schools.com/tags/att_iframe_sandbox.asp

For now it's not a easy task to check this by myself, because my mirror is completely outdated, and i have to recreate my stuff from scratch. I use the Face-Reco-DNN and some display related modules for switching on and off 2 displays depends on who's present in front of the mirror including loading personalized modules inside a carousel. This will take some time. I only can do such tasks afterwork. Or on weekend. I have tons of IoT things lying around and waiting for assembling, changing or creating. Sorry for the long explanation. This have nothing to do with your error. ;-)

**Comment by nygma2004** [comment]
OK, I think I know what the issue is. I tried loading the MM in Chrome on my computer, and I can see these error in the debugger:
```
Refused to display 'http://192.168.1.82/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```
So the browser does not allow loading resources from a different origin. I am not sure why you are not getting this issue, maybe due to the older version. I will try checking this on the main forum as well.

**Comment by coderpussy** [comment]
@nygma2004 it seems like your
```
ipWhitelist: [["192.168.1.0","192.168.1.253"],"127.0.0.1", "::ffff:127.0.0.1", "::1"]
```
is maybe incorrectly setted up. ```192.168.1.0``` means your network itself. But specified is a range? Up to ```192.168.1.253```? For this network the range would be ```["192.168.1.1","192.168.1.254"]``` (includes your gateway if it's located at ```192.168.1.1```). 

Keep in mind if your gateway is also your internet router, you should go sure the connection between each other network have no security lacks.

If you want to completely allow your ```192.168.1.0``` network to access your mirror it would be probably better to setup as ```192.168.1.0/24``` instead. And remove the ```192.168.1.253``` and the range outer brackets.

As i mentioned before, my setting is ```ipWhitelist: []```. So, this means that access is granted from everywhere and i exactly know, what, who or from where is access to my mirror. The default configuration for ```ipWhitelist``` is more useful on public commercial mirror who needs special ip address configuration security.

Maybe you can give it a try to setup first ```ipWhitelist: []```. And check on mirror and chrome browser. In my chrome i can also see the still image. Updated by interval as well. I can't check this for now, i just wrote down what came in my mind. 😀

**Comment by coderpussy** [comment]
Close issue cause of inactivity.
